<?php

namespace DonBundle\Repository;

/**
 * CategorieEquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEquipmentRepository extends \Doctrine\ORM\EntityRepository
{
}
