<?php

namespace DonBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DonBundle\Entity\Equipment;
use DonBundle\Entity\CategorieEquipment;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{

public function findString()
{  return $this->getEntityManager()
    ->createQuery(
        'SELECT p
                FROM DonBundle:Equipment p
                WHERE p.etatEquipment LIKE :str'
    )
    ->setParameter('str', '%'."En cours".'%')
    ->getResult();

}

    public function findbyString()
    {  return $this->getEntityManager()
        ->createQuery(
            'SELECT sum(p.nbEquipment) as nb ,count(p.nomEquipment) as nb1 , count(p.categorieEquipment) as nb2
                FROM DonBundle:Equipment p
                '
        )
      //  ->setParameter('str', '%'."En cours".'%')
        ->getResult();

    }
}


