<?php

namespace DonBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DonBundle\Entity\equipment;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiebyString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT q
                FROM DonBundle:equipment q
                WHERE q.nomEquipment
                LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

}
