<?php

namespace DonBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DonBundle\Entity\Service;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{




    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM DonBundle:Service p
                WHERE p.nomService LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function findbySnom()
    {  return $this->getEntityManager()
        ->createQuery(
            'SELECT count(p.nomService) as nb2
                FROM DonBundle:Service p
                '
        )
        //  ->setParameter('str', '%'."En cours".'%')
        ->getResult();

    }

}
