categorieequipment_index:
    path:     /
    defaults: { _controller: "DonBundle:CategorieEquipment:index" }
    methods:  GET

categorieequipment_show:
    path:     /{id}/show
    defaults: { _controller: "DonBundle:CategorieEquipment:show" }
    methods:  GET

categorieequipment_new:
    path:     /new
    defaults: { _controller: "DonBundle:CategorieEquipment:new" }
    methods:  [GET, POST]

categorieequipment_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonBundle:CategorieEquipment:edit" }
    methods:  [GET, POST]

categorieequipment_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonBundle:CategorieEquipment:delete" }
    methods:  DELETE
