categorieservice_index:
    path:     /
    defaults: { _controller: "DonBundle:CategorieService:index" }
    methods:  GET

categorieservice_show:
    path:     /{id}/show
    defaults: { _controller: "DonBundle:CategorieService:show" }
    methods:  GET

categorieservice_new:
    path:     /new
    defaults: { _controller: "DonBundle:CategorieService:new" }
    methods:  [GET, POST]

categorieservice_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonBundle:CategorieService:edit" }
    methods:  [GET, POST]

categorieservice_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonBundle:CategorieService:delete" }
    methods:  DELETE
