camp_camp:
    resource: "@CampBundle/Resources/config/routing/camp.yml"
    prefix:   /camp

event:
    path:     /event
    defaults: { _controller: EventBundle:Default:index }
refugie_refugie:
    resource: "@CampBundle/Resources/config/routing/refugie.yml"
    prefix:   /refugie
