<?php

namespace CampBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CampBundle\Entity\Camp;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;

/**
 * CampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM CampBundle:Camp p
                WHERE p.nomCamp LIKE :str'
            )
            ->setParameter('str',
                '%'.$str.'%')
            ->getResult();
    }
}
