<?php

namespace CampBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CampBundle\Entity\Refugie;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
/**
 * RefugieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM CampBundle:Refugie p
                WHERE p.nomRefugie LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
