<?php

namespace AppBundle\Repository;

/**
 * MessageMetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageMetaDataRepository extends \Doctrine\ORM\EntityRepository
{
}
