fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

don:
    resource: "@DonBundle/Resources/config/routing.yml"
camp:
    resource: "@CampBundle/Resources/config/routing.yml"

event:
    resource: "@EventBundle/Resources/config/routing.yml"

communication:
    resource: "@CommunicationBundle/Resources/config/routing.yml"
produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /home
CRUDevent:
    path:     /crudE
    defaults: { _controller: EventBundle:Default:afficher}
