communication_commentaire:
    resource: "@CommunicationBundle/Controller/CommentaireController.php"
    type:     annotation

communication_message:
    resource: "@CommunicationBundle/Controller/MessageController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

don:
    resource: "@DonBundle/Resources/config/routing.yml"
camp:
    resource: "@CampBundle/Resources/config/routing.yml"

event:
    resource: "@EventBundle/Resources/config/routing.yml"

communication:
    resource: "@CommunicationBundle/Resources/config/routing.yml"
produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /home

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /mes