<?php

namespace CommunicationBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
use CommunicationBundle\Entity\Annonce;

class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a
                FROM CommunicationBundle:Annonce a
              where  a.titreAnnonce = ?1 "
            )
            ->setParameter(1, $str)
            ->getResult();
    }

    public function statAnn(){

        return $this->getEntityManager()
            ->createQuery(
                "SELECT count(a.id) as nbAnnonce 
                FROM CommunicationBundle:Annonce a 
            "
            )
            ->getResult();
    }

    public function statCom(){

        return $this->getEntityManager()
            ->createQuery(
                "SELECT count(a.id) as nbComm
                FROM CommunicationBundle:Commentaire a 
            "
            )
            ->getResult();
    }
}
