<?php

namespace EventBundle\Repository;

/**
 * InviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInvitById($id)
    {
        $qb = $this->getEntityManager()
            ->createQuery("select i from EventBundle:Invite i where i.evenement=:param")
            ->setParameter('param',$id);
        return $query = $qb->getResult();
    }
}
