<?php

namespace EventBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPartById($id)
    {
        $qb = $this->getEntityManager()
            ->createQuery("select  i from EventBundle:Participation i where i.participant=:param")
            ->setParameter('param',$id);
        return $query = $qb->getResult();
    }
}
